
export const skills = [
  { name: "React", iconId: "react" },
  { name: "JavaScript", iconId: "javascript" },
  { name: "Node.js", iconId: "node-dot-js" },
  { name: "CSS", iconId: "css3" },
  { name: "HTML", iconId: "html5" },
  { name: "Next.js", iconId: "nextjs" },
  { name: "TypeScript", iconId: "typescript" },
  { name: "Axios", iconId: "axios" },
  { name: "MongoDB", iconId: "mongodb" },
  { name: "Material-UI", iconId: "material-ui" },
  { name: "Redux", iconId: "redux" },
  { name: "Express.js", iconId: "express" },
  { name: "Firebase", iconId: "firebase" },
  { name: "Git", iconId: "git" },
  { name: "GitHub", iconId: "github" },
  { name: "VS Code", iconId: "vscode" },
  { name: "Figma", iconId: "figma" },
  { name: "@emotion/styled", iconId: "internet" },
  { name: "Postman", iconId: "postman" },
  { name: "Vite", iconId: "jsvite" },
  { name: "Nodemailer", iconId: "nodemailer" },
  { name: "JWT", iconId: "jwt" },
  { name: "Nodemon", iconId: "nodemon" },
  { name: "Yup", iconId: "yup" },
  { name: "Formik", iconId: "formik" },
  { name: "TailwindCSS", iconId: "tailwindcss" },
  { name: "SASS", iconId: "sass" },
  { name: "CssGrid", iconId: "internet" },
  { name: "Parcel", iconId: "parcel" },
  { name: "i18next", iconId: "i18next" },
  { name: "Vercel", iconId: "vercel" },
  { name: "ChatGPT", iconId: "chatgpt-logo" },
  { name: "REST API", iconId: "rest-api" },
];
